### ISSUE TITLE
Adding documentation on how to build a consortium network

### ISSUE THREAD

**Issue by g2udevelopment** [substrate-developer-hub/substrate-enterprise-sample#50]
First of thanks for this example, for the aspiring enterprise blockchain builder this is a really cool example and shows how to integrate the various parts. 

What I would like if you guys can give an example or some pointers on how to deploy this network so that it functions as a 'private' consortium network.

**Comment by stiiifff** [comment]
Thank you @g2udevelopment for your feedback (and keep it coming) !

Firstly, the enterprise sample's runtime is configured with the [Aura](https://substrate.dev/docs/en/knowledgebase/advanced/consensus#aura) block production mechanism, this is the typical Proof-of-Authority consensus you would find in a private consortium network.
The sample also demonstrates the use of the [Substrate Validator Set pallet](https://github.com/gautamdhameja/substrate-validator-set) which allows to dynamically add / remove validators (via extrinsics), this is a very useful capability in business networks e.g. when a new founding organization joins the industry consortium. You could further extend this capability by combining it with some governance features ... this is left (for now) as a challenge to the readers 😉

Secondly, you can follow the instructions in this tutorial on how to start a private network with multiple nodes (with the built-in Alice, Bob, etc accounts): https://substrate.dev/docs/en/tutorials/start-a-private-network/ 

Also, the Web3 Foundation has more extensive documentation for Network Maintainers.
Most of it applies to Substrate-based consortium networks (if you ignore the Kusama / Polkadot -specific parts):
https://wiki.polkadot.network/docs/en/maintain-index

Let me know if that helps, or if you need more specific guidance.

**Comment by g2udevelopment** [comment]
Thank you @stiiifff for your very detailed answer. The biggest part of my question concerns the step from development(PoC) to a production ready system. So a few question that come to mind are.

- How to secure nodes so that only members of the consortium are able to join the network. 
   There is the possibilty of reserved peers but this requires a lot of synchronization, 
    Another option is to look at building a VPN between the participants 
   Yet another option is to create a semi-open chain in which every one can join by adding a node at pointing to a know boot node (and sync the state) but they are not able to submit extrinsic's.

- How to make sure that all the participants have enough balance to make up for the transaction fee without manual reloading of account balances.

I do think that most of the question are of architectural nature and are question I currently trying to solve/answer myself. So maybe I can even cooperate with you guys you give you some insight in how business what to use this system in practice. Things like Aura and Validator Set pallet are already implemented in my chain.

**Comment by stiiifff** [comment]
Great questions @g2udevelopment ! There is no one single answer to them, and as you mentioned many approches are possible. Below are some proposals, but bear in mind they're biased towards open networks:

- I would argue that, firstly, it'd be good to retain the values of openness & transparency of the technology even though you're in a consortium setup (more on this in the second point); and secondly, you'd have more flexibility / evolvability by enforcing the rules at a runtime level (e.g. using the [Role-based Access Control pallet](https://github.com/gautamdhameja/substrate-rbac)) vs at an infrastructure-level (VPN / network / node). Fork-less runtime upgrades will allow you to more easily adapt whatever logic you've decided to implement. But if you want to do it at a lower-level, it's obviously possible too.
- There are various approaches to this. One way could be to forego all economic aspects and set related chain params to zero (or equivalent) because it's a (private / closed) enterprise consortium chain, but then you'll end moving the cursor towards more & more control, and higher barriers to entry. Which IMHO kind of render moot all the benefits of such tech.
On the other hand, by striving to design a relevant business & token model for the industry / consortium chain with appropriate economic incentives, you then retain native Blockchain capabilities, and you keep the possibility for your chain to become at a later point a Parachain, and to integrate within the wider Polkadot ecosystem. To automate the provisioning of  existential deposits, you could do it from the application side (using JS libs) e.g. sufficient funds could be allocated to know accounts from a pool belonging to the organization those accounts are related to (and different strategies could be applied per org ...).

Thinking along those lines, you start to see that the distinction between public & private chains does not really make sense anymore. Even when thinking about consortium chains, we should always strive to design for open ecosystems / networks.

**Comment by danforbes** [comment]
Very cool discussion, guys. I think it would be difficult for me to compete with the answers @stiiifff has provided, but I will chime in and mention that [the Multisig pallet](https://crates.parity.io/pallet_multisig/index.html) may be useful as a primitive form of governance in a consortium setting.

**Comment by g2udevelopment** [comment]
@stiiifff Totally agree with you on the open aspects of a chain. I think designing a system that is open in principal but has some specific economic and runtime measure in-place to keep it secure for a participating members is the way to go. 

I would love to see more example etc.. evolve in this project (developer-hub) to accommodate for consortium chains.

I think for now this issue contains enough information to help other people with possibly the same questions. I would also love to have some discussion off-github(riot chat would be nice).

Thanks @danforbes for participating.
